# Site settings
title: Mrcatの记录集
permalink: /:year/:month/:title.html
description: 一个用来折腾的算是博客的网站
url: "https://blog.mrcat.me"

# Build settings
safe: true
timezone: Asia/Shanghai
markdown: kramdown
highlighter: none
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - README.md
  - CNAME

defaults:
  -
    scope:
        path: "_post"
    values:
        layout: "post"
  -
    scope:
        path: "_drafts"
    values:
        layout: "post"